apiVersion: apps/v1
kind: Deployment
metadata:
  name: trader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trader
  template:
    metadata:
      labels:
        app: trader
    spec:
      containers:
        - name: trader
          image: jkl315/trader:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: sql-related
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-related
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: sql-related
                  key: POSTGRES_DB
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: sql-related
                  key: DATABASE_URL
            - name: NEXTAUTH_URL
              valueFrom:
                secretKeyRef:
                  name: sql-related
                  key: NEXTAUTH_URL
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: sql-related
                  key: NEXTAUTH_SECRET
          readinessProbe:
            httpGet:
              path: /signin
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /signin
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
