apiVersion: v1
kind: Job
metadata:
  name: prisma-migrate
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: jkl315/trader:prod
          command: ["npx","prisma","migrate","deploy"]
          envFrom:
            - secretRef:
                name: sql-related
      restartPolicy: Never
