apiVersion: v1
kind: Secret
metadata:
    name: sql-related
type: Opaque
data:
    POSTGRES_USER: YWRtaW4= # echo -n 'admin' | base64
    POSTGRES_PASSWORD: RUNFMTc3OVByb2plY3RQR1Bhc3N3b3Jk # echo -n 'ECE1779ProjectPGPassword' | base64
    POSTGRES_DB: YXBwZGI= # echo -n 'appdb' | base64
    DATABASE_URL: cG9zdGdyZXNxbDovL2FkbWluOkVDRTE3NzlQcm9qZWN0UEdQYXNzd29yZEBwb3N0Z3Jlczo1NDMyL2FwcGRi

    NEXTAUTH_URL: aHR0cDovL2xvY2FsaG9zdDozMDAw # echo -n 'http://localhost:3000' | base64
    NEXTAUTH_SECRET: L2dhM09iU1ZyNGxUeW5TSEVKL0xVcUlaaktXZjNDMEtWbEJJZ0krRFVrcktiYjNLVmk2SkJVZ0VSSG13PQ==
