apiVersion: v1
kind: Secret
metadata:
  name: sql-related
type: Opaque
data:
  POSTGRES_USER: YWRtaW4= # echo -n 'admin' | base64
  POSTGRES_PASSWORD: RUNFMTc3OVByb2plY3RQR1Bhc3N3b3Jk # echo -n 'ECE1779ProjectPGPassword' | base64
  POSTGRES_DB: YXBwZGI= # echo -n 'appdb' | base64
