apiVersion: v1
kind: Service
metadata:
  name: trader-service
spec:
  selector:
    app: trader          # Match deployment.spec.template.metadata.labels, which is app=trader
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 3000